version: '3'
services:
  zookeeper:
    image: 'zookeeper:3.4'
    ports:
      - '2181:2181'
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  credit-service:
    build: ./credit-service
    depends_on:
      - kafka
      - mongo
    ports:
      - '8081:8081'
  debit-service:
    build: ./debit-service
    depends_on:
      - kafka
      - mongo
    ports:
      - '8082:8082'
  transfer-service:
    build: ./transfer-service
    depends_on:
      - kafka
      - mongo
    ports:
      - '8083:8083'
  balance-service:
    build: ./balance-service
    depends_on:
      - kafka
      - mongo
    ports:
      - '8084:8084'
  statement-service:
    build: ./statement-service
    depends_on:
      - kafka
      - mongo
    ports:
      - '8085:8085'
